# Generated by Django 5.0.1 on 2024-01-18 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_cartiterm_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartiterm',
            old_name='price',
            new_name='product',
        ),
    ]
